operator_info{
	seq:1
	operator_type:kPalmCheckRegisterLightOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"LegalLightStatus"
			value_type:TypeBool
			bool_value:false
		}
	}
	decision_branches{
		next_seq:2
	}
}

operator_info{
	seq:2
	operator_type:kPalmCheckAEIntensityOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"AEQualityImage"
			value_type:TypeBool
			bool_value:false
		}
	}
	decision_branches{
		next_seq:3
	}
}


operator_info{
	seq:3
	operator_type:kPalmDetectorAeOperator
	decision_branches{
		next_seq:4
	}

}

operator_info{
	seq:4
	operator_type:kPalmMotionPerceptionOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"IsMoving"
			value_type:TypeBool
			bool_value:true
		}
	}
	decision_branches{
		next_seq:5
	}
}

operator_info{
	seq:5
	operator_type:kPalmRegressionOperator
	decision_branches{
		next_seq:6
	}

}
operator_info{
	seq:6
	operator_type:kPalmRegisterRectBoundaryCheckOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"ExpectRect"
			value_type:TypeBool
			bool_value:false
		}
	}
	decision_branches{
		next_seq:7
	}
}

operator_info{
	seq:7
	operator_type:kPalmImgCropOperator
	decision_branches{
		next_seq:8
	}
}

operator_info{
	seq:8
	operator_type:kPalmCheckRegisterIntensityOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"QualityImage"
			value_type:TypeBool
			bool_value:false
		}
	}
	decision_branches{
		next_seq:9
	}
}

operator_info{
	seq:9
	operator_type:kPalmQualityOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"QualityScore"
			value_type:TypeScope
			scope_value{
				low_limit:0.0
				high_limit:0.5
			}
		}

	}
	decision_branches{
		next_seq:10
	}
}

operator_info{
	seq:10
	operator_type:kPalmRegisterQualityOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"RegisterQualityScore"
			value_type:TypeScope
			scope_value{
				low_limit:0.0
				high_limit:0.5
			}
		}

	}
	decision_branches{
		next_seq:11
	}
}

operator_info{
	seq:11
	operator_type:kPalmLivenessOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"LivenessScore"
			value_type:TypeScope
			scope_value{
				low_limit:0.0
				high_limit:0.5
			}
		}

	}
	decision_branches{
		next_seq:12
	}
}

operator_info{
	seq:12
	operator_type:kPalmLivenessColorGrayOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"LivenessColorGrayScore"
			value_type:TypeScope
			scope_value{
				low_limit:0.0
				high_limit:0.5
			}
		}

	}
	decision_branches{
		next_seq:13
	}
}


operator_info{
	seq:13
	operator_type:kPalmSkeletonOperator
	decision_branches{
		next_seq:14
	}
}

operator_info{
	seq:14
	operator_type:kPalmImgNormOperator
	decision_branches{
		next_seq:15
	}
}

operator_info{
	seq:15
	operator_type:kPalmReliabilityRgbOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"ReliabilityRgbScore"
			value_type:TypeScope
			scope_value{
				low_limit:0.0
				high_limit:0.5
			}
		}

	}
	decision_branches{
		next_seq:16
	}
}

operator_info{
	seq:16
	operator_type:kPalmReliabilityIrOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"ReliabilityIrScore"
			value_type:TypeScope
			scope_value{
				low_limit:0.0
				high_limit:0.5
			}
		}

	}
	decision_branches{
		next_seq:17
	}
}

operator_info{
	seq:17
	operator_type:kPalmRegisterReliabilityRgbOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"RegisterReliabilityRgbScore"
			value_type:TypeScope
			scope_value{
				low_limit:0.0
				high_limit:0.5
			}
		}

	}
	decision_branches{
		next_seq:18
	}
}

operator_info{
	seq:18
	operator_type:kPalmRegisterReliabilityIrOperator
	decision_branches{
		next_seq:999
		key_parameters{
			param_name:"RegisterReliabilityIrScore"
			value_type:TypeScope
			scope_value{
				low_limit:0.0
				high_limit:0.5
			}
		}

	}
	decision_branches{
		next_seq:19
	}
}

operator_info{
	seq:19
	operator_type:kPalmRegisterChosenOperator
	decision_branches{
		next_seq:20
		key_parameters{
			param_name:"RecogImgMoal"
			value_type:TypeInt
			int_value:1
		}
	}
	decision_branches{
		next_seq:21
		key_parameters{
			param_name:"RecogImgMoal"
			value_type:TypeInt
			int_value:2
		}
	}
	decision_branches{
		next_seq:22
		key_parameters{
			param_name:"RecogImgMoal"
			value_type:TypeInt
			int_value:3
		}
	}
}


operator_info{
	seq:20
	operator_type:kPalmIrRecognitionOperator
	decision_branches{
		next_seq:1000
	}
}

operator_info{
	seq:21
	operator_type:kPalmRgbRecognitionOperator
	decision_branches{
		next_seq:1000
	}
}

operator_info{
	seq:22
	operator_type:kPalmIrRecognitionOperator
	decision_branches{
		next_seq:23
	}
}

operator_info{
	seq:23
	operator_type:kPalmRgbRecognitionOperator
	decision_branches{
		next_seq:1000
	}
}
