model_config_path:"./palm_models_config.pbtxt"
operator_config{
	operator_name:"PalmRegressionOperator"
	inference_name:"InferencePalmRegression"
	model_name:"palm_regression"
	operator_type:kPalmRegressionOperator
	need_model:true
	enable:true
	param_configs{
		param_name:"PalmRegressionCropRatio"
		param_value:4.0
	}
}
operator_config{
	operator_name:"PalmDetectorOperator"
	inference_name:"InferencePalmAnchorFreeDetector"
	model_name:"palm_ae_detection"
	operator_type:kPalmDetectorAeOperator
	need_model:true
	enable:true
	param_configs{
		param_name:"DetectorConfidence"
		param_value:0.35
	}
	param_configs{
		param_name:"DetectorNms"
		param_value:0.4
	}
	param_configs{
		param_name:"DetectorMinSize"
		param_int_array{
			int_array:8
			int_array:8
			int_array:16
			int_array:16
			int_array:32
			int_array:32
			int_array:64
			int_array:64
			int_array:128
			int_array:128
			int_array:256
			int_array:256
		}
	}
	param_configs{
		param_name:"DetectorSteps"
		param_int_array{
			int_array:8
			int_array:16
			int_array:32
		}
	}
}
operator_config{
	operator_name:"PalmImgCropOperator"
	operator_type:kPalmImgCropOperator
	need_model:false
	enable:true
	param_configs{
		param_name:"CropRatio"
		param_value:1.3
	}
}

operator_config{
	operator_name:"PalmImgCheckIntensityOperator"
	operator_type:kPalmCheckIntensityOperator
	need_model:false
	enable:true
	param_configs{
		param_name:"IrImgLowerLimit"
		param_value:60
	}
	param_configs{
		param_name:"IrImgUpperLimit"
		param_value:180
	}
	param_configs{
		param_name:"RgbImgLowerLimit"
		param_value:80
	}
	param_configs{
		param_name:"RgbImgUpperLimit"
		param_value:210
	}
}



operator_config{
	operator_name:"PalmImgCheckIntensityOperator"
	operator_type:kPalmCheckRegisterIntensityOperator
	need_model:false
	enable:true
	param_configs{
		param_name:"IrImgLowerLimit"
		param_value:70
	}
	param_configs{
		param_name:"IrImgUpperLimit"
		param_value:160
	}
	param_configs{
		param_name:"RgbImgLowerLimit"
		param_value:90
	}
	param_configs{
		param_name:"RgbImgUpperLimit"
		param_value:200
	}
}


operator_config{
	operator_name:"PalmImgCheckAEIntensityOperator"
	operator_type:kPalmCheckAEIntensityOperator
	need_model:false
	enable:true
	param_configs{
		param_name:"IrImgLowerLimit"
		param_value:60
	}
	param_configs{
		param_name:"IrImgUpperLimit"
		param_value:180
	}
	param_configs{
		param_name:"RgbImgLowerLimit"
		param_value:80
	}
	param_configs{
		param_name:"RgbImgUpperLimit"
		param_value:210
	}
}

operator_config{
	operator_name:"PalmImgCheckLightperator"
	operator_type:kPalmCheckLightOperator
	need_model:false
	enable:true
	param_configs{
		param_name:"PSensorLowerLimit"
		param_value:50
	}
	param_configs{
		param_name:"PSensorUpperLimit"
		param_value:150
	}
}

operator_config{
	operator_name:"PalmImgCheckLightperator"
	operator_type:kPalmCheckRegisterLightOperator
	need_model:false
	enable:true
	param_configs{
		param_name:"PSensorLowerLimit"
		param_value:50
	}
	param_configs{
		param_name:"PSensorUpperLimit"
		param_value:120
	}
}

operator_config{
	operator_name:"PalmRectBoundaryCheckOperator"
	operator_type:kPalmRegisterRectBoundaryCheckOperator
	need_model:false
	enable:true
	param_configs{
		param_name:"RectBoundary"
		param_int_array{
			int_array:120
			int_array:170
			int_array:600
			int_array:854
		}
	}
}

operator_config{
	operator_name:"PalmRectBoundaryCheckOperator"
	operator_type:kPalmRectBoundaryCheckOperator
	need_model:false
	enable:true
	param_configs{
		param_name:"RectBoundary"
		param_int_array{
			int_array:30
			int_array:40
			int_array:690
			int_array:984
		}
	}
}

operator_config{
	operator_name:"PalmMotionPerceptionOperator"
	operator_type:kPalmMotionPerceptionOperator
	param_configs{
		param_name:"MotionOffset"
		param_value:16.0
	}
	need_model:false
	enable:true
}


operator_config{
	operator_name:"PalmLivenessCenterOperator"
	inference_name:"InferencePalmLivenessCenter"
	model_name:"palm_ir_liveness"
	operator_type:kPalmLivenessOperator
	need_model:true
	enable:true
	param_configs{
		param_name:"LivenessImgModal"
		param_value:0
	}
	param_configs{
		param_name:"LivenessModelChannel"
		param_value:9
	}
	param_configs{
		param_name:"CropRatio"
		param_value:1.0
	}
}

operator_config{
	operator_name:"PalmQualityOperator"
	inference_name:"InferencePalmQuality128"
	model_name:"palm_quality"
	operator_type:kPalmQualityOperator
	need_model:true
	enable:true
}

operator_config{
	operator_name:"PalmQualityOperator"
	inference_name:"InferencePalmQuality128"
	model_name:"palm_quality_register"
	operator_type:kPalmRegisterQualityOperator
	need_model:true
	enable:true
}

operator_config{
	operator_name:"PalmQualityOperator"
	inference_name:"InferencePalmQualityColorGray"
	model_name:"palm_rgb_liveness"
	operator_type:kPalmLivenessColorGrayOperator
	need_model:true
	enable:true
}

operator_config{
	operator_name:"PalmQualityOperator"
	inference_name:"InferencePalmReliability"
	model_name:"palm_rgb_reliability"
	operator_type:kPalmReliabilityRgbOperator
	need_model:true
	enable:true
}

operator_config{
	operator_name:"PalmQualityOperator"
	inference_name:"InferencePalmReliability"
	model_name:"palm_ir_reliability"
	operator_type:kPalmReliabilityIrOperator
	need_model:true
	enable:true
}

operator_config{
	operator_name:"PalmQualityOperator"
	inference_name:"InferencePalmReliability"
	model_name:"palm_rgb_register_reliability"
	operator_type:kPalmRegisterReliabilityRgbOperator
	need_model:true
	enable:true
}

operator_config{
	operator_name:"PalmQualityOperator"
	inference_name:"InferencePalmReliability"
	model_name:"palm_ir_register_reliability"
	operator_type:kPalmRegisterReliabilityIrOperator
	need_model:true
	enable:true
}


operator_config{
	operator_name:"PalmImgNormOperator"
	operator_type:kPalmImgNormOperator
	need_model:false
	enable:true
}

operator_config{
	operator_name:"PalmRecognitionOperator"
	inference_name:"InferencePalmRecognition"
	model_name:"palmprint_ir_recognition@baseline15_exp23_eval151"
	operator_type:kPalmIrRecognitionOperator
	need_model:true
	need_latest_hash:true
	enable:true
	hash_configs{
		hash_name:"IrLatestHash"
		latest_hash:"palmprint_ir_recognition@baseline15_exp23_eval151"
	}
	param_configs{
		param_name:"RecognitionImgModal"
		param_value:0.0
	}
	param_configs{
		param_name:"RecognitionThreshold"
		param_value:0.7072
	}
}


operator_config{
	operator_name:"PalmRegisterChosenOperator"
	operator_type:kPalmRegisterChosenOperator
	need_model:false
	enable:true
}



operator_config{
	operator_name:"PalmRecognitionOperator"
	inference_name:"InferencePalmRecognition"
	model_name:"palmprint_rgb_recognition@baseline11_exp17_eval177"
	operator_type:kPalmRgbRecognitionOperator
	need_model:true
	need_latest_hash:true
	enable:true
	hash_configs{
		hash_name:"RgbLatestHash"
		latest_hash:"palmprint_rgb_recognition@baseline11_exp17_eval177"
	}
	param_configs{
		param_name:"RecognitionImgModal"
		param_value:2.0
	}
	param_configs{
		param_name:"RecognitionThreshold"
		param_value:0.7253
	}
	
}


operator_config{
	operator_name:"PalmSkeletonOperator"
	inference_name:"InferencePalmSkeleton"
	model_name:"palm_kps"
	operator_type:kPalmSkeletonOperator
	need_model:true
	enable:true
	param_configs{
		param_name:"CropRatio"
		param_value:1.3
	}
	param_configs{
		param_name:"OriginImgWidth"
		param_value:720
	}
	param_configs{
		param_name:"OriginImgHeight"
		param_value:1024
	}
}
